name: make build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libglfw3-dev libglew-dev libstb-dev libglm-dev
        
    - name: make
      run: make
